---
output: github_document
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "80%"
)
```

# A package with R and C++ extensions

## Quickstart

1. Launch RStudio Server and login /r-studio-server.example.com:8787/
1. Open rCppSample.Rproj
1. Select the Build tab and click the Install and Restart button
1. Select the Check button

## Install and run manually

### Build and install on a shell

```bash
cd ~/work
R CMD build rCppSample
R CMD INSTALL rCppSample_0.0.0.9000.tar.gz
```

### Install on R

```r
remotes::install_local("rCppSample_0.0.0.9000.tar.gz", dependencies = "Imports")
```

### Run

```r
library(rCppSample)
rCppSample::popcount(as.raw(c(2, 255)))
rCppSample::popcount(c(1023, 1024, 1025))
```

## Testing

### R code

```r
library(rCppSample)
devtools::test()
coverage_report <- covr::package_coverage()
print(coverage_report)
covr::report(coverage_report, "./coverage_report.html")
lintr::lint_package()
```

### C++ code

```bash
mkdir -p tests/build
cd tests/build
cmake ..
make
make test
cd ~/work/rCppSample/tests/build/CMakeFiles/test_popcount.dir
lcov -d . -c -o coverage.info
lcov -r coverage.info "/usr/*" "*/googletest/*" "/opt/boost*" -o coverageFiltered.info
genhtml -o lcovHtml --num-spaces 4 -s --legend coverageFiltered.info
mkdir -p docs
cd docs
```

## Make documents

```r
devtools::document()
rmarkdown::render("README.Rmd")
```

## Benchmarking

```{r setup_benchmark, echo = FALSE, message = FALSE, cache = TRUE}
library(rCppSample)
library(dplyr)
library(ggplot2)
library(microbenchmark)
library(kableExtra)

popcount_table <- purrr::map_dbl(0:255, function(x) {
  sum(as.numeric(intToBits(as.raw(x))))
})

popcount_raw_r <- function(xs) {
  popcount_table[1 + as.numeric(xs)]
}

popcount_integer_r <- function(xs) {
  popcount_raw_r(bitwAnd(xs, 0xff)) +
    popcount_raw_r(bitwAnd(bitwShiftR(xs, 8), 0xff)) +
    popcount_raw_r(bitwAnd(bitwShiftR(xs, 16), 0xff)) +
    popcount_raw_r(bitwAnd(bitwShiftR(xs, 24), 0xff))
}

n_set_size <- 10000
full_raw_xs <- as.raw(0:255)
n_xs_size <- NROW(full_raw_xs) * n_set_size
raw_set <- rep(full_raw_xs, n_set_size)
integer_set <- as.integer(floor(runif(n = n_xs_size, min = 0, max = 0x7ffffffe)))

stopifnot(NROW(raw_set) == NROW(integer_set))
stopifnot(all(popcount_raw_r(raw_set) == rCppSample::popcount(raw_set)))
stopifnot(all(popcount_integer_r(integer_set) == rCppSample::popcount(integer_set)))
```

```{r run_benchmark, echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE}
invisible(gc())
result <- microbenchmark::microbenchmark(
  popcount_raw_r(raw_set),
  popcount_integer_r(integer_set),
  rCppSample::popcount(raw_set),
  rCppSample::popcount(integer_set),
  times = 100
)
```

```{r draw_benchmark, echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE}
g <- autoplot(result, log = FALSE)
ggsave("benchmark.png", g, width=6, height=3)
plot(g)

df_result <- tibble::as_tibble(summary(result))
min_median <- min(df_result$median)

df_result %>%
  dplyr::select("expr", "mean", "median") %>%
  dplyr::rename(method = expr) %>%
  dplyr::mutate(ratio = median / min_median) %>%
  dplyr::arrange(ratio) %>%
  dplyr::rename(`ratio (median)` = ratio) %>%
  mutate_if(is.numeric, format, digits = 6, nsmall = 4) %>%
  kableExtra::kable()
```
