remotes::install_local("../rCppSample_0.0.0.9000.tar.gz", dependencies = "Imports")
library(rCppSample)
devtools::test()
coverage_report <- covr::package_coverage()
print(coverage_report)
covr::report(coverage_report, "./coverage_report.html")
lintr::lint_package()
devtools::document()
rmarkdown::render("README.Rmd", "github_document")
